"""Opportunity brief markdown renderer — exact format from spec 01 / sample 08a."""

from __future__ import annotations

import re
from datetime import datetime

from automation_miner.schemas import Opportunity


def title_slug(title: str) -> str:
    """Short slug for the brief filename."""
    text = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")
    return text[:60].strip("-") or "opportunity"


def _escape(text: str) -> str:
    return text.replace('"', "'")


def _bullets(items: list[str]) -> str:
    return "\n".join(f"- {item}" for item in items) if items else "- (none identified)"


def _numbered(items: list[str]) -> str:
    return "\n".join(f"{i}. {item}" for i, item in enumerate(items, 1))


def render_brief(opp: Opportunity, run_id: str, date: str | None = None) -> str:
    """Render one AM-XXX brief as self-contained markdown with YAML frontmatter."""
    d = opp.draft
    date = date or f"{datetime.now():%Y-%m-%d}"
    tags = f"[automation, {d.layer.value}, {opp.domain_slug}]"

    impact_rows = "\n".join(
        f"| {r.dimension} | {r.current} | {r.automated} | {r.improvement} |"
        for r in d.impact_analysis
    )
    risk_rows = "\n".join(
        f"| {r.risk} | {r.likelihood.value.upper()[0]} | "
        f"{r.impact.value.upper()[0]} | {r.mitigation} |"
        for r in d.risks
    )

    return f"""---
am-id: "{opp.am_id}"
title: "{_escape(d.title)}"
domain: "{_escape(opp.domain)}"
layer: "{d.layer.value}"
status: "{opp.status.value}"
ice-score: {opp.ice}
impact: {opp.score.impact}
confidence: {opp.score.confidence}
ease: {opp.score.ease}
created: "{date}"
updated: "{date}"
source: "{run_id}"
tags: {tags}
---

# {opp.am_id}: {d.title}

## Problem Statement

{d.problem}

## Proposed Automation

{d.proposed_automation}

## Process Details

### Inputs
{_bullets(d.inputs)}

### Steps
{_numbered(d.steps)}

### Outputs
{_bullets(d.outputs)}

### Human-in-the-Loop Points
{_bullets(d.hitl_points)}

## Feasibility Assessment

### Technical Requirements
{_bullets(d.technical_requirements)}

### Dependencies
{_bullets(d.dependencies)}

### Constraints
{_bullets(d.constraints)}

## Impact Analysis

| Dimension | Current State | Automated State | Improvement |
|-----------|--------------|----------------|-------------|
{impact_rows}

## Implementation Path

### Phase 1: MVP (1-2 weeks)
{_bullets(d.implementation.mvp)}

### Phase 2: Expansion (2-4 weeks)
{_bullets(d.implementation.expansion)}

### Phase 3: Autonomy (4-8 weeks)
{_bullets(d.implementation.autonomy)}

## Risk & Mitigations

| Risk | Likelihood | Impact | Mitigation |
|------|-----------|--------|------------|
{risk_rows}

---

## Self-Improvement

This opportunity was generated by the Automation Miner engine. Track its lifecycle through the pipeline:

- [ ] **Identified** — opportunity brief created
- [ ] **Validated** — domain expert confirmed problem/relevance
- [ ] **Designed** — implementation plan complete
- [ ] **Built** — prototype or MVP shipped
- [ ] **Measured** — actual impact vs. projected impact
- [ ] **Lessons learned** — what did the miner get right/wrong?

Validation criteria:
- Actual time saved vs. estimate
- Error rate improvement vs. estimate
- User satisfaction with automation
- What was missed in the analysis?
"""
