"""Pydantic models for every artifact the pipeline produces.

These are the structured-output contracts between the LLM roles and the
deterministic code. Every model is also the on-disk JSON artifact shape.
The package is split by pipeline phase; import from here.
"""

from automation_miner.schemas.base import (
    ArtifactModel,
    Layer,
    AnalysisMode,
    Level,
    OppStatus,
    Tier,
    Eligibility,
    LAYER_ORDER,
    LAYER_TITLES,
)
from automation_miner.schemas.context import (
    SkippedFile,
    Chunk,
    ContextStats,
    InputQuality,
    RunBudget,
    ContextPacket,
    PolicyClause,
    PolicyReading,
)
from automation_miner.schemas.analysis import (
    EvidenceClaim,
    InputAssessment,
    StakeholderProcess,
    DomainMap,
    OpportunityCandidate,
    PainPoint,
    RankedPain,
    CandidatePortfolio,
    LayerAnalysis,
)
from automation_miner.schemas.opportunity import (
    RiskRow,
    ImpactRow,
    PhasePlan,
    ExternalDataChannel,
    PaymentAction,
    PortfolioScore,
    PortfolioScores,
    RepairVerdict,
    OpportunityDraft,
    Critique,
    ICEScore,
    Opportunity,
    PortfolioStats,
    CRITIQUE_WEIGHTS,
    CRITIQUE_THRESHOLD,
    PUBLICATION_QUALITY_FLOOR,
)
from automation_miner.schemas.run import (
    RoleUsage,
    RunUsage,
    SummaryEntry,
    RunSummary,
    RunManifest,
    StageFailure,
)

__all__ = [
    "AnalysisMode",
    "ArtifactModel",
    "CRITIQUE_THRESHOLD",
    "CRITIQUE_WEIGHTS",
    "CandidatePortfolio",
    "Chunk",
    "ContextPacket",
    "PolicyClause",
    "PolicyReading",
    "ContextStats",
    "Critique",
    "DomainMap",
    "Eligibility",
    "EvidenceClaim",
    "ExternalDataChannel",
    "ICEScore",
    "ImpactRow",
    "InputAssessment",
    "InputQuality",
    "LAYER_ORDER",
    "LAYER_TITLES",
    "Layer",
    "LayerAnalysis",
    "Level",
    "OppStatus",
    "Opportunity",
    "OpportunityCandidate",
    "PainPoint",
    "RankedPain",
    "OpportunityDraft",
    "PUBLICATION_QUALITY_FLOOR",
    "PaymentAction",
    "PortfolioScore",
    "PortfolioScores",
    "RepairVerdict",
    "PhasePlan",
    "PortfolioStats",
    "RiskRow",
    "RoleUsage",
    "RunBudget",
    "RunManifest",
    "RunSummary",
    "RunUsage",
    "SkippedFile",
    "StageFailure",
    "StakeholderProcess",
    "SummaryEntry",
    "Tier",
]
